import { IconType } from "react-icons";

import { BsFillRouterFill } from "react-icons/bs";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiGooglecloud,
  SiDocker,
  SiLaravel,
  SiPhp,
  SiExpress,
  SiMysql,
  SiFirebase,
  SiNgrok,
  SiCpanel,
  SiBootstrap,
  SiTailwindcss,
  SiNodedotjs,
  SiJquery,
  SiBlockchaindotcom,
} from "react-icons/si";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaInstagram,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  googlecloud: SiGooglecloud,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  docker: SiDocker,
  laravel: SiLaravel,
  php: SiPhp,
  express: SiExpress,
  mysql: SiMysql,
  firebase: SiFirebase,
  ngrok: SiNgrok,
  cpanel: SiCpanel,
  bootstrap: SiBootstrap,
  tailwind: SiTailwindcss,
  nodejs: SiNodedotjs,
  jquery: SiJquery,
  blockchain: SiBlockchaindotcom,
  router: BsFillRouterFill,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
